### PR TITLE
Update dependencies, fix vulnerabilities

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
NOTE: I had to modify `samples-nodejs-express-4/config.js` for tests to pass locally.

```diff
@@ -14,7 +14,7 @@ if (fs.existsSync(TESTENV)) {
 var ISSUER = process.env.ISSUER || 'https://{yourOktaDomain}.com/oauth2/default';
 var CLIENT_ID = process.env.CLIENT_ID || '{clientId}';
 var CLIENT_SECRET = process.env.CLIENT_SECRET || '{clientSecret}';
-var SPA_CLIENT_ID = process.env.SPA_CLIENT_ID || '{spaClientId}';
+var SPA_CLIENT_ID = process.env.CLIENT_ID || '{spaClientId}';
 var OKTA_TESTING_DISABLEHTTPSCHECK = process.env.OKTA_TESTING_DISABLEHTTPSCHECK ? true : false;

 module.exports = {
```

**Comment by mraible** [comment]
I tried to upgrade these samples to use the latest version of Vue, but there are parser errors from eslint. I believe these can be fixed by using [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue).

**Comment by aarongranick-okta** [comment]
@mraible Thanks! I will pull these changes into a branch and attempt the Vue update.

**Comment by aarongranick-okta** [comment]
New PR: https://github.com/okta/samples-js-vue/pull/83

**Pull request closed without merging**
